### PR TITLE
Restructure repository with decoupled examples

### PR DESCRIPTION
**Pull request by dpiatek**
Rework the repository to:
- to have an application that is an index and runs all the examples
- each example can be run independently

The second requirement is twofold - we want folks to be able to just look at an isolated example of a feature and we want to use those examples with https://sandpack.codesandbox.io/. There some small compromises made to allow this - the entry point for each example is and `index.tsx` and `App.tsx`, former being used just by the example, latter the component to render. 

Each component has `[name of example]-container example-container` classes. The first class is loaded in the decoupled example, the second in the root app. This is required so we can slightly different styling for both apps.

I've used this opportunity to also update dependencies, most of which had no effect on resulting code apart from `@heroicons` & `random-words`  which needed their imports updated.

I've added a `yarn` `workspace` to make running and managing of dependencies in the repo easier (ie. when developing you just need to run `yarn` once in root).

Note the large amount of lines comes from multiple lock files added.

### CODE REVIEW

**Review by snikidev — APPROVED** [review]
Apart from that minor duplication comment, looks good 👍

**Review by lawrence-forooghian — COMMENTED** [review]
I wasn't intending to look at the code in detail, but thought I'd at least try running the examples to take a look at them. However, when I try to run some of the the individual example apps by following the instructions in the individual `README` files (of the few I tested, I observed it in `vite-member-location` and `vite-live-cursors`), I get an error about `random-words`:

vite-live-cursors error

**Comment by dpiatek** [comment]
thanks @lawrence-forooghian thats weird - I've tested all examples, I'll try a fresh install.

**Comment by dpiatek** [comment]
@lawrence-forooghian indeed! I had to delete my `node_modules` in each example but found the missing deps and updated them in https://github.com/ably-labs/realtime-examples/pull/66/commits/0663a2f033ea0ce3a15524778d8ef7ba09f275c4

**Review by lawrence-forooghian — COMMENTED** [review]
I haven't looked at the code but the examples work 👍

**Pull request merged**
